import { assertStateFacts } from "./validators/stateFacts";

export interface StateInfo {
  slug: string;
  name: string;
  region: string;
  /** Official/majority languages of the state — drives the "state-native" pair archetype
   *  (a page only becomes state-native if the language is also one we offer). */
  officialLanguages: string[];
  /** Named institutions, true for every city in the state. Verify before relying on the
   *  exact name — these get reorganised; verifiedOn tracks when it was last checked. */
  registrationDept: string;
  highCourt: string;
  schoolBoard: string;
  transportAuthority: string;
  homeDeptAttestation: string;
  /** Used only when a City record has no industries/economicNote of its own. */
  industriesFallback: string[];
  economicNoteFallback: string;
  verifiedOn: string;
}

export const states: StateInfo[] = [
  {
    slug: "maharashtra",
    name: "Maharashtra",
    region: "Western India",
    officialLanguages: ["Marathi"],
    registrationDept: "the Department of Registration and Stamps, Maharashtra (IGR Maharashtra)",
    highCourt: "the Bombay High Court",
    schoolBoard: "the Maharashtra State Board of Secondary and Higher Secondary Education",
    transportAuthority: "the Maharashtra Motor Vehicles Department (RTO)",
    homeDeptAttestation: "the Maharashtra Home Department (General Administration Department)",
    industriesFallback: ["manufacturing", "financial and professional services", "trade"],
    economicNoteFallback: "one of India's most industrialised and financially significant states",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "delhi",
    name: "Delhi",
    region: "Northern India",
    officialLanguages: ["Hindi", "Urdu", "Punjabi"],
    registrationDept: "the Revenue Department, Government of NCT of Delhi (Sub-Registrar offices)",
    highCourt: "the Delhi High Court",
    schoolBoard: "the Central Board of Secondary Education (CBSE) and the Directorate of Education, Delhi",
    transportAuthority: "the Delhi Transport Department (RTO)",
    homeDeptAttestation: "the Delhi Home Department (Sub-Divisional Magistrate offices)",
    industriesFallback: ["government administration", "trade and services", "corporate headquarters"],
    economicNoteFallback: "India's national capital and a major administrative and commercial centre",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "karnataka",
    name: "Karnataka",
    region: "Southern India",
    officialLanguages: ["Kannada"],
    registrationDept: "the Department of Stamps and Registration, Karnataka",
    highCourt: "the High Court of Karnataka",
    schoolBoard: "the Karnataka School Examination and Assessment Board",
    transportAuthority: "the Karnataka Transport Department (RTO)",
    homeDeptAttestation: "the Karnataka Home Department",
    industriesFallback: ["information technology and software services", "biotechnology", "aerospace"],
    economicNoteFallback: "home to India's largest concentration of IT and biotechnology companies",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "tamil-nadu",
    name: "Tamil Nadu",
    region: "Southern India",
    officialLanguages: ["Tamil"],
    registrationDept: "the Tamil Nadu Registration Department (Inspector General of Registration)",
    highCourt: "the Madras High Court",
    schoolBoard: "the Tamil Nadu State Board of School Examinations",
    transportAuthority: "the Tamil Nadu Transport Department (RTO)",
    homeDeptAttestation: "the Tamil Nadu Home Department",
    industriesFallback: ["automotive and engineering manufacturing", "textiles", "IT services"],
    economicNoteFallback: "one of India's most industrialised southern states, with a strong automotive and textile manufacturing base",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "west-bengal",
    name: "West Bengal",
    region: "Eastern India",
    officialLanguages: ["Bengali"],
    registrationDept: "the West Bengal Directorate of Registration and Stamp Revenue",
    highCourt: "the Calcutta High Court",
    schoolBoard: "the West Bengal Board of Secondary Education",
    transportAuthority: "the West Bengal Transport Department (RTO)",
    homeDeptAttestation: "the West Bengal Home and Hill Affairs Department",
    industriesFallback: ["jute and textiles", "trade and commerce", "engineering"],
    economicNoteFallback: "a historic trading and manufacturing hub in eastern India",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "telangana",
    name: "Telangana",
    region: "Southern India",
    officialLanguages: ["Telugu", "Urdu"],
    registrationDept: "the Telangana Registration and Stamps Department",
    highCourt: "the High Court for the State of Telangana",
    schoolBoard: "the Telangana State Board of Intermediate Education",
    transportAuthority: "the Telangana Transport Department (RTO)",
    homeDeptAttestation: "the Telangana Home Department",
    industriesFallback: ["information technology and software services", "pharmaceuticals", "biotechnology"],
    economicNoteFallback: "a major IT and pharmaceutical hub centred on Hyderabad",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "gujarat",
    name: "Gujarat",
    region: "Western India",
    officialLanguages: ["Gujarati"],
    registrationDept: "the Gujarat Department of Registration (Superintendent of Stamps)",
    highCourt: "the Gujarat High Court",
    schoolBoard: "the Gujarat Secondary and Higher Secondary Education Board",
    transportAuthority: "the Gujarat Transport Department (RTO)",
    homeDeptAttestation: "the Gujarat Home Department",
    industriesFallback: ["textiles and diamond processing", "chemicals and petrochemicals", "trade and exports"],
    economicNoteFallback: "a major manufacturing and trading state with a large NRI diaspora",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "rajasthan",
    name: "Rajasthan",
    region: "Northern India",
    officialLanguages: ["Hindi"],
    registrationDept: "the Rajasthan Department of Registration and Stamps",
    highCourt: "the Rajasthan High Court",
    schoolBoard: "the Board of Secondary Education, Rajasthan (RBSE)",
    transportAuthority: "the Rajasthan Transport Department (RTO)",
    homeDeptAttestation: "the Rajasthan Home Department",
    industriesFallback: ["tourism and hospitality", "handicrafts and textiles", "mining"],
    economicNoteFallback: "a state with a large tourism economy and long-standing handicraft and textile traditions",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "uttar-pradesh",
    name: "Uttar Pradesh",
    region: "Northern India",
    officialLanguages: ["Hindi", "Urdu"],
    registrationDept: "the Uttar Pradesh Stamp and Registration Department (IGRS UP)",
    highCourt: "the Allahabad High Court",
    schoolBoard: "the Uttar Pradesh Madhyamik Shiksha Parishad (UP Board)",
    transportAuthority: "the Uttar Pradesh Transport Department (RTO)",
    homeDeptAttestation: "the Uttar Pradesh Home Department",
    industriesFallback: ["manufacturing", "IT and business services", "leather and handicrafts"],
    economicNoteFallback: "India's most populous state, with a large and diverse manufacturing base",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "haryana",
    name: "Haryana",
    region: "Northern India",
    officialLanguages: ["Hindi"],
    registrationDept: "the Haryana Department of Revenue and Disaster Management (Registration Wing)",
    highCourt: "the Punjab and Haryana High Court at Chandigarh",
    schoolBoard: "the Board of School Education Haryana (BSEH)",
    transportAuthority: "the Haryana Transport Department (RTO)",
    homeDeptAttestation: "the Haryana Home Department",
    industriesFallback: ["automotive manufacturing", "IT and business process services", "agriculture"],
    economicNoteFallback: "a major automotive-manufacturing and IT-services state bordering Delhi",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "himachal-pradesh",
    name: "Himachal Pradesh",
    region: "Northern India",
    officialLanguages: ["Hindi"],
    registrationDept: "the Himachal Pradesh Department of Revenue (Registration Wing)",
    highCourt: "the Himachal Pradesh High Court",
    schoolBoard: "the Himachal Pradesh Board of School Education",
    transportAuthority: "the Himachal Pradesh Transport Department (RTO)",
    homeDeptAttestation: "the Himachal Pradesh Home Department",
    industriesFallback: ["pharmaceutical manufacturing", "tourism and hospitality", "hydropower"],
    economicNoteFallback: "a hill state with a significant pharmaceutical-manufacturing sector and tourism economy",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "punjab",
    name: "Punjab",
    region: "Northern India",
    officialLanguages: ["Punjabi"],
    registrationDept: "the Punjab Department of Revenue, Rehabilitation and Disaster Management (Registration Wing)",
    highCourt: "the Punjab and Haryana High Court at Chandigarh",
    schoolBoard: "the Punjab School Education Board",
    transportAuthority: "the Punjab Transport Department (RTO)",
    homeDeptAttestation: "the Punjab Department of Home Affairs and Justice",
    industriesFallback: ["agriculture and agro-processing", "light engineering and manufacturing"],
    economicNoteFallback: "an agricultural and light-manufacturing state with a large overseas diaspora",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "andhra-pradesh",
    name: "Andhra Pradesh",
    region: "Southern India",
    officialLanguages: ["Telugu"],
    registrationDept: "the Andhra Pradesh Registration and Stamps Department",
    highCourt: "the High Court of Andhra Pradesh",
    schoolBoard: "the Board of Intermediate Education, Andhra Pradesh",
    transportAuthority: "the Andhra Pradesh Transport Department (RTO)",
    homeDeptAttestation: "the Andhra Pradesh Home Department",
    industriesFallback: ["agriculture and aquaculture", "port operations and heavy industry", "IT services"],
    economicNoteFallback: "a coastal state with significant port and heavy-industry activity",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "arunachal-pradesh",
    name: "Arunachal Pradesh",
    region: "North Eastern India",
    officialLanguages: ["English"],
    registrationDept: "the Arunachal Pradesh Department of Land Management (Registration Wing)",
    highCourt: "the Gauhati High Court (Itanagar Permanent Bench)",
    schoolBoard: "the Central Board of Secondary Education (CBSE)",
    transportAuthority: "the Arunachal Pradesh Transport Department (RTO)",
    homeDeptAttestation: "the Arunachal Pradesh Home Department",
    industriesFallback: ["horticulture and agriculture", "hydropower", "tourism"],
    economicNoteFallback: "a Himalayan border state with an economy centred on agriculture, hydropower and tourism",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "assam",
    name: "Assam",
    region: "North Eastern India",
    officialLanguages: ["Assamese"],
    registrationDept: "the Assam Directorate of Registration",
    highCourt: "the Gauhati High Court",
    schoolBoard: "the Board of Secondary Education, Assam (SEBA)",
    transportAuthority: "the Assam Transport Department (RTO)",
    homeDeptAttestation: "the Assam Home and Political Department",
    industriesFallback: ["tea cultivation and processing", "oil and natural gas", "trade and distribution"],
    economicNoteFallback: "the commercial and administrative gateway to North East India, with a large tea industry",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "bihar",
    name: "Bihar",
    region: "Eastern India",
    officialLanguages: ["Hindi", "Urdu"],
    registrationDept: "the Bihar Registration Department",
    highCourt: "the Patna High Court",
    schoolBoard: "the Bihar School Examination Board (BSEB)",
    transportAuthority: "the Bihar Transport Department (RTO)",
    homeDeptAttestation: "the Bihar Home Department",
    industriesFallback: ["agriculture and food processing", "trade and services"],
    economicNoteFallback: "a densely populated state with an economy centred on agriculture and trade",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "chhattisgarh",
    name: "Chhattisgarh",
    region: "Central India",
    officialLanguages: ["Hindi"],
    registrationDept: "the Chhattisgarh Registration Department",
    highCourt: "the High Court of Chhattisgarh",
    schoolBoard: "the Chhattisgarh Board of Secondary Education",
    transportAuthority: "the Chhattisgarh Transport Department (RTO)",
    homeDeptAttestation: "the Chhattisgarh Home Department",
    industriesFallback: ["steel and mining", "power generation", "agriculture"],
    economicNoteFallback: "a mineral-rich state with a large steel and power-generation industry",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "goa",
    name: "Goa",
    region: "Western India",
    officialLanguages: ["Konkani"],
    registrationDept: "the Goa Department of Registration",
    highCourt: "the Bombay High Court (Goa Bench)",
    schoolBoard: "the Goa Board of Secondary and Higher Secondary Education",
    transportAuthority: "the Goa Transport Department (RTO)",
    homeDeptAttestation: "the Goa Home Department",
    industriesFallback: ["tourism and hospitality", "mining", "pharmaceuticals"],
    economicNoteFallback: "a coastal state with an economy centred on tourism and hospitality",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "jharkhand",
    name: "Jharkhand",
    region: "Eastern India",
    officialLanguages: ["Hindi"],
    registrationDept: "the Jharkhand Registration Department",
    highCourt: "the Jharkhand High Court",
    schoolBoard: "the Jharkhand Academic Council",
    transportAuthority: "the Jharkhand Transport Department (RTO)",
    homeDeptAttestation: "the Jharkhand Home Department",
    industriesFallback: ["mining and minerals", "steel manufacturing", "heavy engineering"],
    economicNoteFallback: "a mineral-rich state with a large steel and heavy-engineering industry",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "kerala",
    name: "Kerala",
    region: "Southern India",
    officialLanguages: ["Malayalam"],
    registrationDept: "the Kerala Registration Department",
    highCourt: "the High Court of Kerala at Ernakulam",
    schoolBoard: "the Kerala Board of Public Examinations",
    transportAuthority: "the Kerala Motor Vehicles Department (RTO)",
    homeDeptAttestation: "the Kerala General Administration (Political) Department",
    industriesFallback: ["tourism", "marine products and spice exports", "healthcare services"],
    economicNoteFallback: "a state with one of India's largest overseas-employment corridors to the Gulf",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "madhya-pradesh",
    name: "Madhya Pradesh",
    region: "Central India",
    officialLanguages: ["Hindi"],
    registrationDept: "the Madhya Pradesh Registration Department",
    highCourt: "the Madhya Pradesh High Court at Jabalpur",
    schoolBoard: "the Madhya Pradesh Board of Secondary Education",
    transportAuthority: "the Madhya Pradesh Transport Department (RTO)",
    homeDeptAttestation: "the Madhya Pradesh Home Department",
    industriesFallback: ["agriculture and agro-processing", "pharmaceuticals", "automobile manufacturing"],
    economicNoteFallback: "a central Indian state with a growing pharmaceutical and automobile manufacturing base",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "manipur",
    name: "Manipur",
    region: "North Eastern India",
    officialLanguages: ["Meiteilon (Manipuri)"],
    registrationDept: "the Manipur Registration Department",
    highCourt: "the High Court of Manipur",
    schoolBoard: "the Board of Secondary Education, Manipur",
    transportAuthority: "the Manipur Transport Department (RTO)",
    homeDeptAttestation: "the Manipur Home Department",
    industriesFallback: ["handloom and handicrafts", "agriculture", "trade with Myanmar"],
    economicNoteFallback: "a North Eastern border state with a strong handloom and handicraft tradition",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "meghalaya",
    name: "Meghalaya",
    region: "North Eastern India",
    officialLanguages: ["English"],
    registrationDept: "the Meghalaya Registration Department",
    highCourt: "the High Court of Meghalaya",
    schoolBoard: "the Meghalaya Board of School Education",
    transportAuthority: "the Meghalaya Transport Department (RTO)",
    homeDeptAttestation: "the Meghalaya Home Department",
    industriesFallback: ["coal and mineral mining", "tourism", "agriculture"],
    economicNoteFallback: "a North Eastern hill state with an economy centred on mining, agriculture and tourism",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "mizoram",
    name: "Mizoram",
    region: "North Eastern India",
    officialLanguages: ["English", "Mizo"],
    registrationDept: "the Mizoram Registration Department",
    highCourt: "the Gauhati High Court (Aizawl Bench)",
    schoolBoard: "the Mizoram Board of School Education",
    transportAuthority: "the Mizoram Transport Department (RTO)",
    homeDeptAttestation: "the Mizoram Home Department",
    industriesFallback: ["horticulture", "bamboo-based industries", "trade with Myanmar"],
    economicNoteFallback: "a North Eastern border state with an economy centred on horticulture and bamboo-based industries",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "nagaland",
    name: "Nagaland",
    region: "North Eastern India",
    officialLanguages: ["English"],
    registrationDept: "the Nagaland Registration Department",
    highCourt: "the Gauhati High Court (Kohima Bench)",
    schoolBoard: "the Nagaland Board of School Education",
    transportAuthority: "the Nagaland Transport Department (RTO)",
    homeDeptAttestation: "the Nagaland Home Department",
    industriesFallback: ["agriculture and horticulture", "handloom and handicrafts", "tourism"],
    economicNoteFallback: "a North Eastern hill state with an economy centred on agriculture, handicrafts and tourism",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "odisha",
    name: "Odisha",
    region: "Eastern India",
    officialLanguages: ["Odia"],
    registrationDept: "the Odisha Registration Department",
    highCourt: "the Orissa High Court",
    schoolBoard: "the Board of Secondary Education, Odisha",
    transportAuthority: "the Odisha Transport Department (RTO)",
    homeDeptAttestation: "the Odisha Home Department",
    industriesFallback: ["mining and metals", "port operations", "agriculture"],
    economicNoteFallback: "a mineral-rich coastal state with a large mining and metals industry",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "sikkim",
    name: "Sikkim",
    region: "North Eastern India",
    officialLanguages: ["English", "Nepali"],
    registrationDept: "the Sikkim Registration Department",
    highCourt: "the High Court of Sikkim",
    schoolBoard: "the Sikkim Human Resource Development Department (Board of Secondary Education)",
    transportAuthority: "the Sikkim Transport Department (RTO)",
    homeDeptAttestation: "the Sikkim Home Department",
    industriesFallback: ["tourism", "hydropower", "organic agriculture"],
    economicNoteFallback: "a Himalayan state with an economy centred on tourism, hydropower and organic agriculture",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "tripura",
    name: "Tripura",
    region: "North Eastern India",
    officialLanguages: ["Bengali", "Kokborok"],
    registrationDept: "the Tripura Registration Department",
    highCourt: "the High Court of Tripura",
    schoolBoard: "the Tripura Board of Secondary Education",
    transportAuthority: "the Tripura Transport Department (RTO)",
    homeDeptAttestation: "the Tripura Home Department",
    industriesFallback: ["agriculture and rubber cultivation", "trade with Bangladesh", "handloom"],
    economicNoteFallback: "a North Eastern border state with strong trade and cultural ties to Bangladesh",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "uttarakhand",
    name: "Uttarakhand",
    region: "Northern India",
    officialLanguages: ["Hindi"],
    registrationDept: "the Uttarakhand Registration Department",
    highCourt: "the High Court of Uttarakhand",
    schoolBoard: "the Uttarakhand Board of School Education",
    transportAuthority: "the Uttarakhand Transport Department (RTO)",
    homeDeptAttestation: "the Uttarakhand Home Department",
    industriesFallback: ["pharmaceutical and industrial manufacturing", "tourism and pilgrimage", "hydropower"],
    economicNoteFallback: "a Himalayan state with a growing industrial-manufacturing belt and a large pilgrimage-tourism economy",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "jammu-and-kashmir",
    name: "Jammu and Kashmir",
    region: "Northern India",
    officialLanguages: ["Urdu", "Kashmiri", "Hindi"],
    registrationDept: "the Jammu and Kashmir Registration Department",
    highCourt: "the High Court of Jammu and Kashmir and Ladakh",
    schoolBoard: "the Jammu and Kashmir State Board of School Education",
    transportAuthority: "the Jammu and Kashmir Transport Department (RTO)",
    homeDeptAttestation: "the Jammu and Kashmir Home Department",
    industriesFallback: ["handicrafts and handlooms", "horticulture", "tourism"],
    economicNoteFallback: "a Union Territory with an economy centred on horticulture, handicrafts and tourism",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "ladakh",
    name: "Ladakh",
    region: "Northern India",
    officialLanguages: ["Hindi", "English"],
    registrationDept: "the Ladakh Registration Department",
    highCourt: "the High Court of Jammu and Kashmir and Ladakh",
    schoolBoard: "the Jammu and Kashmir State Board of School Education",
    transportAuthority: "the Ladakh Transport Department (RTO)",
    homeDeptAttestation: "the Ladakh Home Department",
    industriesFallback: ["tourism", "handicrafts", "agriculture and horticulture"],
    economicNoteFallback: "a high-altitude Union Territory with an economy centred on tourism and handicrafts",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "puducherry",
    name: "Puducherry",
    region: "Southern India",
    officialLanguages: ["Tamil", "French", "English"],
    registrationDept: "the Puducherry Registration Department",
    highCourt: "the Madras High Court",
    schoolBoard: "the Directorate of School Education, Puducherry",
    transportAuthority: "the Puducherry Transport Department (RTO)",
    homeDeptAttestation: "the Puducherry Home Department",
    industriesFallback: ["tourism and hospitality", "manufacturing", "trade"],
    economicNoteFallback: "a coastal Union Territory with a French colonial heritage and a tourism-driven economy",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "andaman-and-nicobar-islands",
    name: "Andaman and Nicobar Islands",
    region: "Southern India",
    officialLanguages: ["Hindi", "English"],
    registrationDept: "the Andaman and Nicobar Islands Registration Department",
    highCourt: "the Calcutta High Court (Circuit Bench at Port Blair)",
    schoolBoard: "the Central Board of Secondary Education (CBSE)",
    transportAuthority: "the Andaman and Nicobar Transport Department (RTO)",
    homeDeptAttestation: "the Andaman and Nicobar Islands Home Department",
    industriesFallback: ["tourism and hospitality", "fisheries", "agriculture"],
    economicNoteFallback: "an island Union Territory with an economy centred on tourism and fisheries",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "lakshadweep",
    name: "Lakshadweep",
    region: "Southern India",
    officialLanguages: ["Malayalam"],
    registrationDept: "the Lakshadweep Registration Department",
    highCourt: "the Kerala High Court",
    schoolBoard: "the Central Board of Secondary Education (CBSE)",
    transportAuthority: "the Lakshadweep Transport Department (RTO)",
    homeDeptAttestation: "the Lakshadweep Home Department",
    industriesFallback: ["fisheries", "coconut and coir products", "tourism"],
    economicNoteFallback: "a small island Union Territory with an economy centred on fisheries and coconut cultivation",
    verifiedOn: "2026-08-18",
  },
  {
    slug: "dadra-and-nagar-haveli-and-daman-and-diu",
    name: "Dadra and Nagar Haveli and Daman and Diu",
    region: "Western India",
    officialLanguages: ["Gujarati", "Hindi"],
    registrationDept: "the Dadra and Nagar Haveli and Daman and Diu Registration Department",
    highCourt: "the Bombay High Court",
    schoolBoard: "the Directorate of Education, Dadra and Nagar Haveli and Daman and Diu",
    transportAuthority: "the Dadra and Nagar Haveli and Daman and Diu Transport Department (RTO)",
    homeDeptAttestation: "the Dadra and Nagar Haveli and Daman and Diu Home Department",
    industriesFallback: ["manufacturing", "tourism", "fisheries"],
    economicNoteFallback: "a small industrial Union Territory bordering Gujarat and Maharashtra",
    verifiedOn: "2026-08-18",
  },
];

export const statesBySlug: Record<string, StateInfo> = Object.fromEntries(
  states.map((state) => [state.slug, state])
);

assertStateFacts(states);
